package pocketbase

import (
	"database/sql/driver"
	"encoding/json"
	"time"
)

// DefaultDateLayout specifies the default PocketBase date strings layout.
const DefaultDateLayout = "2006-01-02 15:04:05.000Z"

// NowDateTime returns new DateTime instance with the current local time.
func NowDateTime() DateTime {
	return DateTime{t: time.Now()}
}

// ParseDateTime creates a new DateTime from the provided value
// (a time.Time, a DateTime, a string in DefaultDateLayout/RFC3339, a Unix
// timestamp, etc.).
func ParseDateTime(value any) (DateTime, error) {
	d := DateTime{}
	err := d.Scan(value)
	return d, err
}

// DateTime represents a time.Time instance in UTC that is wrapped and
// serialized using the PocketBase default date layout.
//
// It is wire-compatible with github.com/pocketbase/pocketbase/tools/types.DateTime
// and is provided so that the client (and the code generated by pbc-gen) do not
// need to import the PocketBase module.
type DateTime struct {
	t time.Time
}

// Time returns the internal time.Time instance.
func (d DateTime) Time() time.Time {
	return d.t
}

// Add returns a new DateTime based on the current DateTime + the specified duration.
func (d DateTime) Add(duration time.Duration) DateTime {
	d.t = d.t.Add(duration)
	return d
}

// Sub returns a time.Duration by subtracting the specified DateTime from the current one.
func (d DateTime) Sub(u DateTime) time.Duration {
	return d.Time().Sub(u.Time())
}

// AddDate returns a new DateTime based on the current one + duration.
func (d DateTime) AddDate(years, months, days int) DateTime {
	d.t = d.t.AddDate(years, months, days)
	return d
}

// After reports whether the current DateTime instance is after u.
func (d DateTime) After(u DateTime) bool {
	return d.Time().After(u.Time())
}

// Before reports whether the current DateTime instance is before u.
func (d DateTime) Before(u DateTime) bool {
	return d.Time().Before(u.Time())
}

// Compare compares the current DateTime instance with u.
// It returns -1 if the current instance is before u, +1 if after, or 0 if equal.
func (d DateTime) Compare(u DateTime) int {
	return d.Time().Compare(u.Time())
}

// Equal reports whether the current DateTime and u represent the same time instant.
func (d DateTime) Equal(u DateTime) bool {
	return d.Time().Equal(u.Time())
}

// Unix returns the current DateTime as a Unix time (seconds since epoch).
func (d DateTime) Unix() int64 {
	return d.Time().Unix()
}

// IsZero checks whether the current DateTime instance has zero time value.
func (d DateTime) IsZero() bool {
	return d.Time().IsZero()
}

// String serializes the current DateTime instance into a formatted UTC date string.
// The zero value is serialized to an empty string.
func (d DateTime) String() string {
	t := d.Time()
	if t.IsZero() {
		return ""
	}
	return t.UTC().Format(DefaultDateLayout)
}

// MarshalJSON implements the json.Marshaler interface.
func (d DateTime) MarshalJSON() ([]byte, error) {
	return []byte(`"` + d.String() + `"`), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (d *DateTime) UnmarshalJSON(b []byte) error {
	var raw string
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	return d.Scan(raw)
}

// Value implements the driver.Valuer interface.
func (d DateTime) Value() (driver.Value, error) {
	return d.String(), nil
}

// Scan implements the sql.Scanner interface to scan the provided value
// into the current DateTime instance.
func (d *DateTime) Scan(value any) error {
	switch v := value.(type) {
	case time.Time:
		d.t = v
	case DateTime:
		d.t = v.Time()
	case string:
		if v == "" {
			d.t = time.Time{}
		} else {
			t, ok := parseTimeString(v)
			if !ok {
				return &time.ParseError{Layout: DefaultDateLayout, Value: v}
			}
			d.t = t
		}
	case int:
		d.t = time.Unix(int64(v), 0)
	case int64:
		d.t = time.Unix(v, 0)
	case int32:
		d.t = time.Unix(int64(v), 0)
	case uint:
		d.t = time.Unix(int64(v), 0)
	case uint64:
		d.t = time.Unix(int64(v), 0)
	case uint32:
		d.t = time.Unix(int64(v), 0)
	case float64:
		d.t = time.Unix(int64(v), 0)
	default:
		str, ok := value.(string)
		if !ok {
			str = ""
		}
		if str == "" {
			d.t = time.Time{}
		} else {
			t, ok := parseTimeString(str)
			if !ok {
				return &time.ParseError{Layout: DefaultDateLayout, Value: str}
			}
			d.t = t
		}
	}

	return nil
}

// parseTimeString parses a date string using the PocketBase default layout
// first, then falls back to common time layouts (RFC3339, RFC822, ...).
func parseTimeString(value string) (time.Time, bool) {
	if t, err := time.Parse(DefaultDateLayout, value); err == nil {
		return t, true
	}
	for _, layout := range []string{
		time.RFC3339,
		time.RFC3339Nano,
		time.RFC1123Z,
		time.RFC1123,
		time.RFC822Z,
		time.RFC822,
		time.RFC850,
		time.ANSIC,
		time.UnixDate,
		time.RubyDate,
	} {
		if t, err := time.Parse(layout, value); err == nil {
			return t, true
		}
	}
	return time.Time{}, false
}
