package pocketbase

import (
	"encoding/json"
)

// GeoPoint represents a geographical point (latitude/longitude), matching the
// wire format of github.com/pocketbase/pocketbase/tools/types.GeoPoint so that
// the client (and code generated by pbc-gen) do not need to import the
// PocketBase module.
type GeoPoint struct {
	Lon float64 `json:"lon"`
	Lat float64 `json:"lat"`
}

// String returns the JSON representation of the GeoPoint.
func (p GeoPoint) String() string {
	raw, _ := json.Marshal(p)
	return string(raw)
}
