package generator

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"text/template"
)

// Exercise the current flattened schema through generation, compilation, and writes.
func TestGeneratedCurrentSchemaContracts(t *testing.T) {
	dir := t.TempDir()
	schema := `[
 {"id":"users_id","name":"users","type":"auth","fields":[
  {"name":"id","type":"text","system":true,"required":true},
  {"name":"email","type":"email","system":true,"required":true},
  {"name":"emailVisibility","type":"bool","system":true,"required":true},
  {"name":"verified","type":"bool","system":true,"required":true},
  {"name":"password","type":"password","system":true,"hidden":true,"required":true},
  {"name":"tokenKey","type":"text","system":true,"hidden":true},
  {"name":"name","type":"text"},
  {"name":"score","type":"number"},
  {"name":"secret","type":"text","hidden":true},
  {"name":"joined","type":"autodate","onCreate":true},
  {"name":"created","type":"autodate","onCreate":true},
  {"name":"updated","type":"autodate","onUpdate":true},
  {"name":"status","type":"select","maxSelect":1,"values":["active","inactive"]},
  {"name":"avatar","type":"file","maxSelect":1,"thumbs":["50x50"]}
 ]},
 {"id":"posts_id","name":"posts","type":"base","fields":[
  {"name":"title","type":"text","required":true},
  {"name":"author","type":"relation","collectionId":"users_id","maxSelect":1},
  {"name":"members","type":"relation","collectionId":"users_id","maxSelect":5},
  {"name":"internal","type":"relation","collectionId":"internal_id","maxSelect":1},
  {"name":"superuser","type":"relation","collectionId":"super_id","maxSelect":1},
  {"name":"published","type":"autodate","onCreate":true,"required":true},
  {"name":"files","type":"file","maxSelect":5},
  {"name":"tags","type":"select","maxSelect":5,"values":["one","two"]}
 ]},
 {"id":"internal_id","name":"_internal","type":"base","system":true},
 {"id":"super_id","name":"_superusers","type":"auth","system":true}
 ]`
	schemaPath := filepath.Join(dir, "schema.json")
	if err := os.WriteFile(schemaPath, []byte(schema), 0600); err != nil {
		t.Fatal(err)
	}
	schemas, err := LoadSchema(schemaPath)
	if err != nil {
		t.Fatal(err)
	}
	data := BuildTemplateData(schemas, "models", GenerateOptions{Enums: true, Relations: true, Files: true})
	if len(data.Collections) != 2 || len(data.RelationTypes) != 1 || data.RelationTypes[0].TargetTypeName != "Users" {
		t.Fatalf("system collections or their relation helpers were generated: %+v", data)
	}
	templateFile, err := os.ReadFile("../../cmd/pbc-gen/template.go.tpl")
	if err != nil {
		t.Fatal(err)
	}
	tpl, err := template.New("models").Parse(string(templateFile))
	if err != nil {
		t.Fatal(err)
	}
	var generated bytes.Buffer
	if err := tpl.Execute(&generated, data); err != nil {
		t.Fatal(err)
	}
	for _, forbidden := range []string{"TokenKey", "Secret", "type Internal", "type Superusers"} {
		if strings.Contains(generated.String(), forbidden) {
			t.Fatalf("generated forbidden field/type %s", forbidden)
		}
	}
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	mod, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	modText := strings.Replace(string(mod), "module github.com/mrchypark/pocketbase-client", "module generated-contracts", 1)
	modText += "\nrequire github.com/mrchypark/pocketbase-client v0.0.0\nreplace github.com/mrchypark/pocketbase-client => " + root + "\n"
	sum, err := os.ReadFile(filepath.Join(root, "go.sum"))
	if err != nil {
		t.Fatal(err)
	}
	for name, content := range map[string][]byte{
		"models.go": generated.Bytes(), "models_test.go": []byte(generatedContractTest),
		"go.mod": []byte(modText), "go.sum": sum,
	} {
		if err := os.WriteFile(filepath.Join(dir, name), content, 0600); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command("go", "test", "-mod=mod", "-run", "TestGeneratedContracts", "-count=1", ".")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated contracts failed: %v\n%s", err, output)
	}
}

const generatedContractTest = `package models
import (
 "encoding/json"
 "testing"
)
func TestGeneratedContracts(t *testing.T) {
 patch := NewUsers()
 patch.SetName("renamed")
 if len(patch.ToMap()) != 1 { t.Fatalf("partial update sends unset auth fields: %v", patch.ToMap()) }
 for _, key := range []string{"email", "emailVisibility", "verified", "password", "passwordConfirm", "oldPassword"} {
  if _, ok := patch.ToMap()[key]; ok { t.Fatalf("partial update sends %s", key) }
 }
 patch.SetEmail("")
 if patch.Email == nil || *patch.Email != "" { t.Fatal("cannot explicitly clear email") }
 u := NewUsers()
 if err := json.Unmarshal([]byte("{\"email\":\"read@example.com\",\"emailVisibility\":true,\"verified\":true,\"name\":\"reader\",\"joined\":\"2026-10-07 00:00:00.000Z\",\"password\":\"ignored\",\"passwordConfirm\":\"ignored\",\"oldPassword\":\"ignored\"}"), u); err != nil { t.Fatal(err) }
 if u.Email == nil || *u.Email != "read@example.com" || u.EmailVisibility == nil || !*u.EmailVisibility || u.Verified == nil || !*u.Verified || u.Joined == nil || u.Joined.IsZero() { t.Fatalf("read fields lost: %+v", u) }
 for _, key := range []string{"password", "passwordConfirm", "oldPassword", "joined", "created", "updated"} {
  if _, ok := u.ToMap()[key]; ok { t.Fatalf("read model writes %s", key) }
 }
 u.SetPassword("new-password")
 u.SetPasswordConfirm("new-password")
 u.SetOldPassword("old-password")
 u.SetEmailVisibility(false)
 u.SetVerified(false)
 u.SetScore(0)
 u.SetName("")
 u.SetStatus(UsersStatusActive)
 u.SetAvatar("avatar.png")
 body, err := json.Marshal(u.ToMap()); if err != nil { t.Fatal(err) }
 var values map[string]any
 if err := json.Unmarshal(body, &values); err != nil { t.Fatal(err) }
 for key, want := range map[string]any{"email":"read@example.com", "password":"new-password", "passwordConfirm":"new-password", "oldPassword":"old-password", "emailVisibility":false, "verified":false, "score":float64(0), "name":""} {
  if got, ok := values[key]; !ok || got != want { t.Fatalf("write %s = %v (present %v), want %v", key, got, ok, want) }
 }
 body, err = json.Marshal(u); if err != nil { t.Fatal(err) }
 values = nil
 if err := json.Unmarshal(body, &values); err != nil { t.Fatal(err) }
 for _, key := range []string{"password", "passwordConfirm", "oldPassword", "tokenKey"} {
  if _, ok := values[key]; ok { t.Fatalf("model JSON leaks %s", key) }
 }
 p := NewPosts()
 if got, ok := p.ToMap()["title"]; !ok || got != "" { t.Fatal("ordinary required field semantics changed") }
 if err := json.Unmarshal([]byte("{\"published\":\"2026-10-07 00:00:00.000Z\",\"author\":\"user-id\",\"members\":[\"user-id\"],\"files\":[\"one.png\"],\"tags\":[\"one\"]}"), p); err != nil { t.Fatal(err) }
 if p.Published.IsZero() || p.Author == nil || *p.Author != "user-id" || len(p.Members) != 1 || len(p.Files) != 1 || len(p.Tags) != 1 { t.Fatalf("base fields lost: %+v", p) }
 if _, ok := p.ToMap()["published"]; ok { t.Fatal("writes required autodate") }
 p.SetMembers([]string{})
 p.SetFiles([]string{})
 p.SetTags([]string{})
 body, err = json.Marshal(p.ToMap()); if err != nil { t.Fatal(err) }
 values = nil
 if err := json.Unmarshal(body, &values); err != nil { t.Fatal(err) }
 for _, key := range []string{"members", "files", "tags"} {
  if got, ok := values[key].([]any); !ok || len(got) != 0 { t.Fatalf("cannot clear %s: %v", key, values[key]) }
 }
 if len((UsersRelations{NewUsersRelation("user-id")}).IDs()) != 1 || !IsValidUsersStatusType(UsersStatusActive) || NewFileReference("one.png", "id", "posts", "files").Filename() != "one.png" { t.Fatal("enhanced helpers broken") }
}
`
