name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Format
      run: gofmt -w . && git diff --exit-code
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test ./...
    - name: Race Test
      run: go test -race ./...
    - name: Bench Test
      run: go test -bench=. -benchmem ./...